### PR TITLE
Clamp the value between 0 and 1 to avoid tinygradient errors.

### LINKED ISSUE #342: Issues updating discord server status
### image

`[DiscordServerStatus][1] Generating message content for update...
C:\Users\Administrator\Desktop\InvasionSquadJS\node_modules\tinygradient\index.js:198
        throw new Error('Position must be between 0 and 1');
              ^

Error: Position must be between 0 and 1
    at computeAt (C:\Users\Administrator\Desktop\InvasionSquadJS\node_modules\tinygradient\index.js:198:15)
    at TinyGradient.rgbAt (C:\Users\Administrator\Desktop\InvasionSquadJS\node_modules\tinygradient\index.js:408:16)
    at DiscordServerStatus.generateMessage (file:///C:/Users/Administrator/Desktop/InvasionSquadJS/squad-server/plugins/discord-server-status.js:110:12)
    at DiscordServerStatus.updateMessages (file:///C:/Users/Administrator/Desktop/InvasionSquadJS/squad-server/plugins/discord-base-message-updater.js:151:41)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)

Node.js v18.16.1`

### Squad Information
 * SquadJS Version: 4.0.1
 * Squad Version: Most up to date

If potentially relevant, please provide regarding the state of the Squad server at the time of error, e.g. the current layer.

### System Information
 * Operating System: Windows Server 2019
 * NodeJS Version: 18.16.1
 * Yarn Version: v1.22.19

### PR DESCRIPTION
**Pull request by mxrcode**
Previously, we could get a coefficient greater than 1, causing SquadJS to crash. One case is described [here](https://github.com/Team-Silver-Sphere/SquadJS/issues/342).
Now we clamp the ratio between 0 and 1, which prevents an error related to tinygradient

### CODE REVIEW

**Review by fantinodavide — APPROVED** [review]
Looks good to me

File: squad-server/plugins/discord-server-status.js [hunk 1]
```diff
@@ -99,6 +99,10 @@ export default class DiscordServerStatus extends DiscordBaseMessageUpdater {
     // Set footer.
     embed.setFooter(COPYRIGHT_MESSAGE);
 
+    // Clamp the ratio between 0 and 1 to avoid tinygradient errors.
+    const ratio = this.server.a2sPlayerCount / (this.server.publicSlots + this.server.reserveSlots);
+    const clampedRatio = Math.min(1, Math.max(0, ratio));
+
```
Comment (werewolfboy13) [inline squad-server/plugins/discord-server-status.js]: Please run `yarn lint`. There is a space it is axing here.

**Review by werewolfboy13 — CHANGES_REQUESTED** [review]

File: squad-server/plugins/discord-server-status.js (hunk 1 above)
Comment (mxrcode) [reply squad-server/plugins/discord-server-status.js]: Yes, I apologize. I made the original changes using the github editor without running lint.

**Review by werewolfboy13 — APPROVED** [review]
